spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: embedded


---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/springbatch?useUnicode=true&characterEncoding=utf8
      username: ljw
      password: test1234!
      driver-class-name: com.mysql.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
#      table-prefix: SYSTEM_ #SYSTEM_로 Table 생성
    job:
#      enabled: false #자동실행방지
#      names: batchJob1
      names: ${job.name:NONE} #실행시점에 Binding Program Argument : --job.name=batchJob1 -> 없으면 NONE으로 실행
